name: Push-to-EC2

# Trigger deployment only on push to main branch
on:
  push:
    branches:
      - main
      
jobs:
  deploy:
    name: Deploy to EC2 on main branch push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the files
        uses: actions/checkout@v4

      - name: SSH & Deploy to VM
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.RESUME_EC2_SSH }}
          script: |
           cd /home/user1
           rm -rf my-resume
           git clone https://github.com/monaliptl/Deploy-Resume-on-EC2-with-CI-CD-
           cd my-resume
           docker build -t my-resume .
           docker stop my-resume || true
           docker rm my-resume || true
           docker run -d --name my-resume -p 80:80 my-resume
